# https://gohugo.io/getting-started/configuration/
baseURL: https://NomadWest.org
languageCode: en-us
title: Nomadic Westward - Dev
theme: ["hugo-cloak-email", "PaperMod"]

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
